//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Globalization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labyrinth.Root.Globalization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Debug and Trace Mode.
        /// </summary>
        internal static string str_MainDialog_DebugMode {
            get {
                return ResourceManager.GetString("str_MainDialog_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E&amp;xit.
        /// </summary>
        internal static string str_MainDialog_Exit {
            get {
                return ResourceManager.GetString("str_MainDialog_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Map.
        /// </summary>
        internal static string str_MainDialog_File {
            get {
                return ResourceManager.GetString("str_MainDialog_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Language.
        /// </summary>
        internal static string str_MainDialog_Language {
            get {
                return ResourceManager.GetString("str_MainDialog_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;New.
        /// </summary>
        internal static string str_MainDialog_New {
            get {
                return ResourceManager.GetString("str_MainDialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Load.
        /// </summary>
        internal static string str_MainDialog_Open {
            get {
                return ResourceManager.GetString("str_MainDialog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Learn.
        /// </summary>
        internal static string str_MainDialog_Process {
            get {
                return ResourceManager.GetString("str_MainDialog_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Save creature selected.
        /// </summary>
        internal static string str_MainDialog_Save {
            get {
                return ResourceManager.GetString("str_MainDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Start learning.
        /// </summary>
        internal static string str_MainDialog_Start {
            get {
                return ResourceManager.GetString("str_MainDialog_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S&amp;top learning.
        /// </summary>
        internal static string str_MainDialog_Stop {
            get {
                return ResourceManager.GetString("str_MainDialog_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Style.
        /// </summary>
        internal static string str_MainDialog_Style {
            get {
                return ResourceManager.GetString("str_MainDialog_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ca&amp;ncel.
        /// </summary>
        internal static string str_NewDialog_Cancel {
            get {
                return ResourceManager.GetString("str_NewDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Columns.
        /// </summary>
        internal static string str_NewDialog_Columns {
            get {
                return ResourceManager.GetString("str_NewDialog_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;OK.
        /// </summary>
        internal static string str_NewDialog_OK {
            get {
                return ResourceManager.GetString("str_NewDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Rows.
        /// </summary>
        internal static string str_NewDialog_Rows {
            get {
                return ResourceManager.GetString("str_NewDialog_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New :.
        /// </summary>
        internal static string str_NewDialog_Title {
            get {
                return ResourceManager.GetString("str_NewDialog_Title", resourceCulture);
            }
        }
    }
}
